import * as path from 'path';
import { writeFile, todayISO } from '../utils';
import { WebsiteData } from '../collectors/website';
import { WaybackData } from '../collectors/wayback';
import { DnsData } from '../collectors/dns';
import { TechStackData } from '../collectors/techstack';

interface CollectedData {
  website?: WebsiteData;
  wayback?: WaybackData;
  dns?: DnsData;
  tech?: TechStackData;
}

export function generateCorporateFiles(dossierDir: string, companyName: string, data: CollectedData): number {
  let count = 0;
  const today = todayISO();

  // README.md
  const desc = data.website?.description || 'Intelligence dossier — research in progress.';
  writeFile(path.join(dossierDir, 'README.md'), `---
title: "${companyName} Intelligence Dossier"
type: reference
last_updated: ${today}
---

# ${companyName} — Intelligence Dossier

**${desc}**

> **AI agents:** Start with [ROUTER.md](ROUTER.md) to find any answer in 2 reads.

## Navigation

| # | Section | Start reading |
|---|---------|--------------|
| 1 | [1_corporate/](1_corporate/_MOC.md) | Identity, registrations, certifications |
| 2 | [2_people/](2_people/_MOC.md) | Org structure, profiles |
| 3 | [3_products/](3_products/_MOC.md) | Products, services, pricing |
| 4 | [4_suppliers/](4_suppliers/_MOC.md) | Supplier relationships |
| 5 | [5_customers/](5_customers/_MOC.md) | Clients, prospects |
| 6 | [6_competitors/](6_competitors/_MOC.md) | Competitive landscape |
| 7 | [7_financials/](7_financials/_MOC.md) | Revenue, valuation |
| 8 | [8_marketing/](8_marketing/_MOC.md) | Marketing, events |
| 9 | [9_brand/](9_brand/_MOC.md) | Brand identity |
| 10 | [10_timeline/](10_timeline/_MOC.md) | History |
| 11 | [11_analysis/](11_analysis/_MOC.md) | Analysis, risks |
| 12 | [12_industry/](12_industry/_MOC.md) | Industry context |

*Generated by Company Dossier VS Code Extension on ${today}.*
`);
  count++;

  // 1_corporate/identity.md
  const w = data.website;
  const schemaName = w?.schemaOrg?.name || companyName;
  const schemaAddr = w?.schemaOrg?.address ? JSON.stringify(w.schemaOrg.address, null, 2) : 'Not found in schema.org';
  writeFile(path.join(dossierDir, '1_corporate', 'identity.md'), `---
title: "Corporate Identity"
type: reference
domain: corporate
confidence: ${w?.error ? 'low' : 'moderate'}
last_updated: ${today}
---

# Corporate Identity

| Field | Value | Source |
|-------|-------|--------|
| Company name | ${schemaName} | ${w ? 'Schema.org / HTML' : 'User input'} |
| Website | ${w?.url || 'N/A'} | User input |
| Page title | ${w?.title || 'N/A'} | HTML \`<title>\` |
| Description | ${w?.description || 'N/A'} | Meta description |

## Social Media Links

${w?.socialLinks?.length ? w.socialLinks.map(l => '- ' + l).join('\n') : 'None found on homepage.'}

## Contact Information

**Emails found:** ${w?.emails?.length ? w.emails.join(', ') : 'None found'}
**Phones found:** ${w?.phones?.length ? w.phones.join(', ') : 'None found'}

## Schema.org Data

\`\`\`json
${w?.schemaOrg ? JSON.stringify(w.schemaOrg, null, 2) : 'No schema.org JSON-LD found on homepage.'}
\`\`\`
`);
  count++;

  // 1_corporate/tech_stack.md
  if (data.tech) {
    const t = data.tech;
    writeFile(path.join(dossierDir, '1_corporate', 'tech_stack.md'), `---
title: "Tech Stack"
type: reference
domain: corporate
confidence: high
last_updated: ${today}
---

# Tech Stack

| Component | Value | Confidence |
|-----------|-------|-----------|
| CMS | ${t.cms} | ${t.cms !== 'Unknown' ? 'High' : 'Low'} |
| Generator | ${t.metaGenerator || 'Not detected'} | ${t.metaGenerator ? 'High' : 'Low'} |
| CDN | ${t.cdn || 'Not detected'} | ${t.cdn ? 'High' : 'Low'} |
| Frameworks | ${t.frameworks.length ? t.frameworks.join(', ') : 'Not detected'} | Moderate |

## Analytics

${t.analyticsIds.length ? t.analyticsIds.map(id => '- `' + id + '`').join('\n') : 'No Google Analytics IDs detected.'}

## Tag Manager

${t.gtmIds.length ? t.gtmIds.map(id => '- `' + id + '`').join('\n') : 'No GTM container detected.'}

## Advertising Pixels

${t.adPixels.length ? t.adPixels.map(p => '- ' + p).join('\n') : 'No ad pixels detected.'}
`);
    count++;
  }

  // 1_corporate/contacts.md
  if (data.dns) {
    const d = data.dns;
    writeFile(path.join(dossierDir, '1_corporate', 'contacts.md'), `---
title: "Contacts & Email Infrastructure"
type: reference
domain: corporate
confidence: high
last_updated: ${today}
---

# Contacts & Email Infrastructure

## Email Provider

**${d.emailProvider}** (detected from MX records)

## MX Records

${d.mxRecords.map(r => `| ${r.priority} | ${r.exchange} |`).join('\n') || 'No MX records found.'}

## SPF Record

\`${d.spfRecord || 'No SPF record found'}\`

## DMARC Policy

\`${d.dmarcRecord || 'No DMARC record found'}\`

## Verification Tokens

${d.verificationTokens.length ? d.verificationTokens.map(t => '- `' + t + '`').join('\n') : 'None found.'}

## Subdomains Detected

${d.subdomains.length ? d.subdomains.map(s => '- ' + s).join('\n') : 'No subdomains detected via CNAME.'}
`);
    count++;
  }

  // 10_timeline/website_evolution.md
  if (data.wayback && !data.wayback.error) {
    const wb = data.wayback;
    const firstDate = wb.firstCapture ? `${wb.firstCapture.slice(0,4)}-${wb.firstCapture.slice(4,6)}-${wb.firstCapture.slice(6,8)}` : 'Unknown';
    const lastDate = wb.lastCapture ? `${wb.lastCapture.slice(0,4)}-${wb.lastCapture.slice(4,6)}-${wb.lastCapture.slice(6,8)}` : 'Unknown';
    writeFile(path.join(dossierDir, '10_timeline', 'website_evolution.md'), `---
title: "Website Evolution"
type: reference
domain: timeline
confidence: high
last_updated: ${today}
---

# Website Evolution (Wayback Machine)

| Metric | Value |
|--------|-------|
| First capture | ${firstDate} |
| Last capture | ${lastDate} |
| Total captures | ${wb.totalCaptures} |
| Unique URLs | ${wb.uniqueUrls.length} |
| PDFs discovered | ${wb.pdfUrls.length} |
| Deleted pages | ${wb.deletedPages.length} |

## PDF Documents Found

${wb.pdfUrls.length ? wb.pdfUrls.map(u => '- ' + u).join('\n') : 'No PDFs found in Wayback captures.'}

## Deleted Pages (Were 200, Now Gone)

${wb.deletedPages.length ? wb.deletedPages.slice(0, 30).map(u => '- ' + u).join('\n') : 'No deleted pages detected.'}

## All Unique URLs (first ${Math.min(wb.uniqueUrls.length, 100)})

${wb.uniqueUrls.slice(0, 100).map(u => '- ' + u).join('\n')}
`);
    count++;
  }

  // 11_analysis/executive_brief.md
  writeFile(path.join(dossierDir, '11_analysis', 'executive_brief.md'), `---
title: "Executive Brief"
type: analysis
domain: strategic
confidence: low
last_updated: ${today}
---

# Executive Brief: ${companyName}

## Summary

${w?.description || '[Company description — requires manual research]'}

**Website:** ${w?.url || 'N/A'}
**CMS:** ${data.tech?.cms || 'Unknown'}
**Email Provider:** ${data.dns?.emailProvider || 'Unknown'}
**Wayback First Seen:** ${data.wayback?.firstCapture ? data.wayback.firstCapture.slice(0,4) + '-' + data.wayback.firstCapture.slice(4,6) : 'Unknown'}

## What's Been Collected (Automated)

- [x] Homepage crawled (title, description, schema.org, social links)
- [${data.wayback ? 'x' : ' '}] Wayback Machine history (${data.wayback?.totalCaptures || 0} captures)
- [${data.dns ? 'x' : ' '}] DNS reconnaissance (email provider, SPF, DMARC)
- [${data.tech ? 'x' : ' '}] Tech stack extracted (CMS, analytics, pixels)

## What Requires Manual Research

- [ ] Revenue and financials
- [ ] Team roster and org chart
- [ ] Supplier relationships
- [ ] Customer identification
- [ ] Competitive landscape
- [ ] Industry context
- [ ] Risk assessment

*This brief was auto-generated. Manual research will dramatically improve it.*
`);
  count++;

  return count;
}
