import * as path from 'path';
import { writeFile, todayISO } from '../utils';
import { WebsiteData } from '../collectors/website';
import { WaybackData } from '../collectors/wayback';
import { DnsData } from '../collectors/dns';
import { TechStackData } from '../collectors/techstack';
import { SearchData } from '../collectors/search';
import { CrawledPage, LLMSynthesis } from '../agent';

interface CollectedData {
  website?: WebsiteData;
  wayback?: WaybackData;
  dns?: DnsData;
  tech?: TechStackData;
  search?: SearchData;
  crawledPages?: CrawledPage[];
  llmSynthesis?: LLMSynthesis;
}

export function generateCorporateFiles(dossierDir: string, companyName: string, data: CollectedData): number {
  let count = 0;
  const today = todayISO();
  const w = data.website;
  const crawlCount = data.crawledPages?.filter(p => p.status === 'ok').length || 0;
  const websitePageCount = w?.pageCount || 0;
  const totalPages = websitePageCount + crawlCount;
  const hasLLM = !!data.llmSynthesis;

  // =========================================================================
  // README.md
  // =========================================================================
  const desc = w?.description || 'Intelligence dossier — research in progress.';

  writeFile(path.join(dossierDir, 'README.md'), `---
title: "${companyName} Intelligence Dossier"
type: reference
last_updated: ${today}
---

# ${companyName} — Intelligence Dossier

**${desc}**

> **AI agents:** Start with [ROUTER.md](ROUTER.md) to find any answer in 2 reads.

## Collection Summary

| Source | Status | Items |
|--------|--------|-------|
| Homepage crawl | ${w && !w.error ? 'Complete' : 'Failed'} | title, meta, schema.org |
| Deep page crawl | ${totalPages > 1 ? 'Complete' : 'Skipped'} | ${totalPages} pages |
| Wayback Machine | ${data.wayback && !data.wayback.error ? 'Complete' : 'Skipped'} | ${data.wayback?.totalCaptures || 0} captures, ${data.wayback?.pdfUrls.length || 0} PDFs |
| DNS recon | ${data.dns && !data.dns.error ? 'Complete' : 'Failed'} | ${data.dns?.mxRecords.length || 0} MX, ${data.dns?.subdomains.length || 0} subdomains |
| Tech stack | ${data.tech ? 'Complete' : 'Skipped'} | ${data.tech?.cms || 'Unknown'} CMS |
| Public search | ${data.search ? 'Complete' : 'Skipped'} | ${data.search?.usaSpendingContracts.length || 0} contracts, ${data.search?.socialProfiles.length || 0} social profiles |
| AI analysis | ${hasLLM ? 'Complete' : 'Skipped (no API key)'} | ${hasLLM ? 'Executive brief, SWOT, findings' : 'N/A'} |

## Navigation

| # | Section | Start reading |
|---|---------|--------------|
| 1 | [1_corporate/](1_corporate/_MOC.md) | Identity, registrations, certifications |
| 2 | [2_people/](2_people/_MOC.md) | Org structure, profiles |
| 3 | [3_products/](3_products/_MOC.md) | Products, services, pricing |
| 4 | [4_suppliers/](4_suppliers/_MOC.md) | Supplier relationships |
| 5 | [5_customers/](5_customers/_MOC.md) | Clients, prospects |
| 6 | [6_competitors/](6_competitors/_MOC.md) | Competitive landscape |
| 7 | [7_financials/](7_financials/_MOC.md) | Revenue, valuation |
| 8 | [8_marketing/](8_marketing/_MOC.md) | Marketing, events, social |
| 9 | [9_brand/](9_brand/_MOC.md) | Brand identity |
| 10 | [10_timeline/](10_timeline/_MOC.md) | History |
| 11 | [11_analysis/](11_analysis/_MOC.md) | Analysis, risks, SWOT |
| 12 | [12_industry/](12_industry/_MOC.md) | Industry context |

*Generated by Company Dossier VS Code Extension on ${today}.*
`);
  count++;

  // =========================================================================
  // 1_corporate/identity.md
  // =========================================================================
  const schemaName = w?.schemaOrg?.name || companyName;
  const allEmails = w?.allEmails || w?.emails || [];
  const allPhones = w?.allPhones || w?.phones || [];

  writeFile(path.join(dossierDir, '1_corporate', 'identity.md'), `---
title: "Corporate Identity"
type: reference
domain: corporate
confidence: ${w?.error ? 'low' : 'moderate'}
last_updated: ${today}
---

# Corporate Identity

| Field | Value | Source |
|-------|-------|--------|
| Company name | ${schemaName} | ${w ? 'Schema.org / HTML' : 'User input'} |
| Website | ${w?.url || 'N/A'} | User input |
| Page title | ${w?.title || 'N/A'} | HTML \`<title>\` |
| Description | ${w?.description || 'N/A'} | Meta description |
| Pages crawled | ${totalPages} | Website crawler |

## Social Media Links

${w?.socialLinks?.length ? w.socialLinks.map(l => '- ' + l).join('\n') : 'None found on website.'}

## Contact Information

**Emails found (${allEmails.length}):** ${allEmails.length ? allEmails.join(', ') : 'None found'}
**Phones found (${allPhones.length}):** ${allPhones.length ? allPhones.join(', ') : 'None found'}

## Schema.org Data

\`\`\`json
${w?.schemaOrg ? JSON.stringify(w.schemaOrg, null, 2) : 'No schema.org JSON-LD found on homepage.'}
\`\`\`
`);
  count++;

  // =========================================================================
  // 1_corporate/tech_stack.md
  // =========================================================================
  if (data.tech) {
    const t = data.tech;
    const sourceNote = totalPages > 1
      ? `Extracted from ${totalPages} pages (homepage + ${totalPages - 1} internal pages).`
      : 'Extracted from homepage only.';

    writeFile(path.join(dossierDir, '1_corporate', 'tech_stack.md'), `---
title: "Tech Stack"
type: reference
domain: corporate
confidence: high
last_updated: ${today}
---

# Tech Stack

> ${sourceNote}

| Component | Value | Confidence |
|-----------|-------|-----------|
| CMS | ${t.cms} | ${t.cms !== 'Unknown' ? 'High' : 'Low'} |
| Generator | ${t.metaGenerator || 'Not detected'} | ${t.metaGenerator ? 'High' : 'Low'} |
| CDN | ${t.cdn || 'Not detected'} | ${t.cdn ? 'High' : 'Low'} |
| Frameworks | ${t.frameworks.length ? t.frameworks.join(', ') : 'Not detected'} | Moderate |

## Analytics

${t.analyticsIds.length ? t.analyticsIds.map(id => '- `' + id + '`').join('\n') : 'No Google Analytics IDs detected.'}

## Tag Manager

${t.gtmIds.length ? t.gtmIds.map(id => '- `' + id + '`').join('\n') : 'No GTM container detected.'}

## Advertising Pixels

${t.adPixels.length ? t.adPixels.map(p => '- ' + p).join('\n') : 'No ad pixels detected.'}
`);
    count++;
  }

  // =========================================================================
  // 1_corporate/contacts.md
  // =========================================================================
  if (data.dns) {
    const d = data.dns;
    writeFile(path.join(dossierDir, '1_corporate', 'contacts.md'), `---
title: "Contacts & Email Infrastructure"
type: reference
domain: corporate
confidence: high
last_updated: ${today}
---

# Contacts & Email Infrastructure

## Email Provider

**${d.emailProvider}** (detected from MX records)

## MX Records

| Priority | Exchange |
|----------|----------|
${d.mxRecords.map(r => `| ${r.priority} | ${r.exchange} |`).join('\n') || '| -- | No MX records found |'}

## SPF Record

\`${d.spfRecord || 'No SPF record found'}\`

## DMARC Policy

\`${d.dmarcRecord || 'No DMARC record found'}\`

## Verification Tokens

${d.verificationTokens.length ? d.verificationTokens.map(t => '- `' + t + '`').join('\n') : 'None found.'}

## Subdomains Detected

${d.subdomains.length ? d.subdomains.map(s => '- ' + s).join('\n') : 'No subdomains detected via CNAME.'}
`);
    count++;
  }

  // =========================================================================
  // 3_products/portfolio_overview.md — from product/service pages in crawl
  // =========================================================================
  const allPages = [
    ...(w?.pages || []).map(p => ({ url: p.url, title: p.title, textContent: p.textContent, status: 'ok' as const })),
    ...(data.crawledPages || []).filter(p => p.status === 'ok').map(p => {
      const text = p.html
        .replace(/<script[^>]*>[\s\S]*?<\/script>/gi, '')
        .replace(/<style[^>]*>[\s\S]*?<\/style>/gi, '')
        .replace(/<[^>]+>/g, ' ')
        .replace(/\s+/g, ' ')
        .trim();
      return { url: p.url, title: p.title, textContent: text, status: 'ok' as const };
    })
  ];

  const productPages = allPages.filter(p =>
    /product|service|solution|offering|pricing|feature|platform|catalog/i.test(p.url + ' ' + p.title)
  );

  if (productPages.length > 0) {
    const pageEntries = productPages.map(p => {
      const snippet = (p.textContent || '').slice(0, 300).replace(/\|/g, '/').replace(/\n/g, ' ');
      return `| [${p.title || p.url}](${p.url}) | ${snippet}... |`;
    });

    writeFile(path.join(dossierDir, '3_products', 'portfolio_overview.md'), `---
title: "Products & Services Portfolio"
type: reference
domain: products
confidence: moderate
last_updated: ${today}
---

# Products & Services Portfolio

> Auto-detected from ${productPages.length} product/service pages found during crawl.

## Detected Product/Service Pages

| Page | Description |
|------|-------------|
${pageEntries.join('\n')}

## Page URLs

${productPages.map(p => `- [${p.title || 'Untitled'}](${p.url})`).join('\n')}

*Requires manual review to confirm products, pricing, and categorization.*
`);
    count++;
  }

  // =========================================================================
  // 8_marketing/social_media.md — from discovered social profiles
  // =========================================================================
  const allSocial: Array<{ platform: string; url: string; source: string }> = [];
  const socialSeen = new Set<string>();

  if (data.search?.socialProfiles) {
    for (const p of data.search.socialProfiles) {
      const key = p.platform + ':' + p.url;
      if (!socialSeen.has(key)) {
        socialSeen.add(key);
        allSocial.push(p);
      }
    }
  }

  if (w?.socialLinks) {
    for (const link of w.socialLinks) {
      let platform = 'Other';
      if (/linkedin/i.test(link)) { platform = 'LinkedIn'; }
      else if (/twitter|x\.com/i.test(link)) { platform = 'Twitter/X'; }
      else if (/facebook/i.test(link)) { platform = 'Facebook'; }
      else if (/instagram/i.test(link)) { platform = 'Instagram'; }
      else if (/youtube/i.test(link)) { platform = 'YouTube'; }
      else if (/tiktok/i.test(link)) { platform = 'TikTok'; }
      else if (/github/i.test(link)) { platform = 'GitHub'; }

      const key = platform + ':' + link;
      if (!socialSeen.has(key)) {
        socialSeen.add(key);
        allSocial.push({ platform, url: link, source: 'website HTML' });
      }
    }
  }

  if (allSocial.length > 0) {
    const byPlatform = new Map<string, typeof allSocial>();
    for (const p of allSocial) {
      if (!byPlatform.has(p.platform)) { byPlatform.set(p.platform, []); }
      byPlatform.get(p.platform)!.push(p);
    }

    let platformSections = '';
    for (const [platform, platformProfiles] of byPlatform) {
      platformSections += `\n### ${platform}\n\n`;
      for (const p of platformProfiles) {
        platformSections += `- [${p.url}](${p.url}) *(${p.source})*\n`;
      }
    }

    writeFile(path.join(dossierDir, '8_marketing', 'social_media.md'), `---
title: "Social Media Presence"
type: reference
domain: marketing
confidence: moderate
last_updated: ${today}
---

# Social Media Presence

> ${allSocial.length} social profiles discovered across ${byPlatform.size} platforms.

## Summary

| Platform | Profiles Found |
|----------|---------------|
${[...byPlatform.entries()].map(([p, list]) => `| ${p} | ${list.length} |`).join('\n')}

## Profiles
${platformSections}

*Follower counts, posting frequency, and engagement metrics require manual collection.*
`);
    count++;
  }

  // =========================================================================
  // 7_financials/federal_contracts.md — USASpending data
  // =========================================================================
  if (data.search && data.search.usaSpendingContracts.length > 0) {
    const contracts = data.search.usaSpendingContracts;
    const totalValue = data.search.usaSpendingTotal || contracts.reduce((sum, c) => sum + c.totalObligation, 0);
    const totalAwards = data.search.usaSpendingAwards || contracts.length;

    writeFile(path.join(dossierDir, '7_financials', 'federal_contracts.md'), `---
title: "Federal Contracts (USASpending)"
type: reference
domain: financials
confidence: high
last_updated: ${today}
---

# Federal Contracts

> ${totalAwards} total awards found on USASpending.gov (showing top ${contracts.length}). Total obligated: $${Math.round(totalValue).toLocaleString()}

## Contracts

| Award ID | Agency | Amount | Period | Description |
|----------|--------|--------|--------|-------------|
${contracts.map(c =>
  `| ${c.awardId} | ${c.awardingAgency} | $${Math.round(c.totalObligation).toLocaleString()} | ${c.startDate} - ${c.endDate} | ${(c.description || '').slice(0, 80)} |`
).join('\n')}

## Agency Distribution

${(() => {
  const agencyMap = new Map<string, number>();
  for (const c of contracts) {
    agencyMap.set(c.awardingAgency, (agencyMap.get(c.awardingAgency) || 0) + c.totalObligation);
  }
  return [...agencyMap.entries()]
    .sort((a, b) => b[1] - a[1])
    .map(([agency, total]) => `- **${agency}**: $${Math.round(total).toLocaleString()}`)
    .join('\n');
})()}
`);
    count++;
  }

  // =========================================================================
  // 10_timeline/website_evolution.md — with growth rate & content distribution
  // =========================================================================
  if (data.wayback && !data.wayback.error) {
    const wb = data.wayback;

    const contentTypeDist = wb.contentTypeDistribution || {};
    const hasContentTypes = Object.keys(contentTypeDist).length > 0;

    const firstYear = wb.firstCapture ? wb.firstCapture.slice(0, 4) : '';
    const lastYear = wb.lastCapture ? wb.lastCapture.slice(0, 4) : '';
    const yearsActive = firstYear && lastYear ? parseInt(lastYear) - parseInt(firstYear) : 0;

    let timelineSection = '';
    if (wb.captureTimeline && wb.captureTimeline.length > 0) {
      const yearCounts = new Map<string, number>();
      for (const entry of wb.captureTimeline) {
        const year = entry.month.slice(0, 4);
        yearCounts.set(year, (yearCounts.get(year) || 0) + entry.count);
      }
      timelineSection = `## Captures by Year

| Year | Captures |
|------|----------|
${[...yearCounts.entries()].map(([year, ct]) => `| ${year} | ${ct} |`).join('\n')}
`;
    }

    writeFile(path.join(dossierDir, '10_timeline', 'website_evolution.md'), `---
title: "Website Evolution"
type: reference
domain: timeline
confidence: high
last_updated: ${today}
---

# Website Evolution (Wayback Machine)

## Key Metrics

| Metric | Value |
|--------|-------|
| First capture | ${wb.firstCapture || 'Unknown'} |
| Last capture | ${wb.lastCapture || 'Unknown'} |
| Years active | ${yearsActive > 0 ? yearsActive + ' years' : 'Unknown'} |
| Total captures | ${wb.totalCaptures} |
| Unique URLs | ${wb.uniqueUrls.length} |
| PDFs discovered | ${wb.pdfUrls.length} |
| Deleted pages | ${wb.deletedPages.length} |
${wb.capturesPerMonth ? `| Avg captures/month | ${wb.capturesPerMonth} |` : ''}
${yearsActive > 0 && wb.uniqueUrls.length > 0 ? `| Avg URLs/year | ${Math.round(wb.uniqueUrls.length / yearsActive)} |` : ''}

${wb.siteGrowthSummary ? `## Growth Summary\n\n${wb.siteGrowthSummary}\n` : ''}

${hasContentTypes ? `## Content Type Distribution

| Type | Count | % |
|------|-------|---|
${Object.entries(contentTypeDist)
  .sort((a, b) => b[1] - a[1])
  .map(([type, ct]) => `| ${type} | ${ct} | ${wb.uniqueUrls.length > 0 ? Math.round(ct / wb.uniqueUrls.length * 100) : 0}% |`)
  .join('\n')}
` : ''}

${timelineSection}

## PDF Documents Found

${wb.pdfUrls.length ? wb.pdfUrls.map(u => '- ' + u).join('\n') : 'No PDFs found in Wayback captures.'}

${wb.pdfWaybackUrls && wb.pdfWaybackUrls.length > 0 ? `### Wayback Playback Links

${wb.pdfWaybackUrls.map(u => '- ' + u).join('\n')}
` : ''}

## Deleted Pages (Were 200, Now Gone)

${wb.deletedPages.length ? wb.deletedPages.slice(0, 30).map(u => '- ' + u).join('\n') : 'No deleted pages detected.'}
${wb.deletedPages.length > 30 ? `\n*...and ${wb.deletedPages.length - 30} more.*` : ''}

## All Unique URLs (first ${Math.min(wb.uniqueUrls.length, 100)})

${wb.uniqueUrls.slice(0, 100).map(u => '- ' + u).join('\n')}
${wb.uniqueUrls.length > 100 ? `\n*...and ${wb.uniqueUrls.length - 100} more.*` : ''}
`);
    count++;
  }

  // =========================================================================
  // 11_analysis/executive_brief.md — AI-generated or template
  // =========================================================================
  if (data.llmSynthesis?.executiveBrief) {
    writeFile(path.join(dossierDir, '11_analysis', 'executive_brief.md'), `---
title: "Executive Brief"
type: analysis
domain: strategic
confidence: moderate
last_updated: ${today}
generated_by: claude-sonnet-4
---

# Executive Brief: ${companyName}

${data.llmSynthesis.executiveBrief}

---

## What's Been Collected (Automated)

- [x] Homepage crawled (title, description, schema.org, social links)
- [${totalPages > 1 ? 'x' : ' '}] Deep page crawl (${totalPages} pages)
- [${data.wayback && !data.wayback.error ? 'x' : ' '}] Wayback Machine history (${data.wayback?.totalCaptures || 0} captures)
- [${data.dns && !data.dns.error ? 'x' : ' '}] DNS reconnaissance (email provider, SPF, DMARC)
- [${data.tech ? 'x' : ' '}] Tech stack extracted (CMS, analytics, pixels)
- [${data.search ? 'x' : ' '}] Public search (USASpending, social profiles)
- [x] AI synthesis (Claude analysis of all collected data)

## What Requires Manual Research

${data.llmSynthesis.manualResearchNeeded || `- [ ] Revenue and financials
- [ ] Team roster and org chart
- [ ] Supplier relationships
- [ ] Customer identification
- [ ] Competitive landscape
- [ ] Industry context`}

*This brief was generated by Claude (claude-sonnet-4) from ${totalPages} crawled pages and automated collection data.*
`);
  } else {
    writeFile(path.join(dossierDir, '11_analysis', 'executive_brief.md'), `---
title: "Executive Brief"
type: analysis
domain: strategic
confidence: low
last_updated: ${today}
---

# Executive Brief: ${companyName}

## Summary

${w?.description || '[Company description -- requires manual research]'}

**Website:** ${w?.url || 'N/A'}
**CMS:** ${data.tech?.cms || 'Unknown'}
**Email Provider:** ${data.dns?.emailProvider || 'Unknown'}
**Wayback First Seen:** ${data.wayback?.firstCapture || 'Unknown'}

## What's Been Collected (Automated)

- [x] Homepage crawled (title, description, schema.org, social links)
- [${totalPages > 1 ? 'x' : ' '}] Deep page crawl (${totalPages} pages)
- [${data.wayback && !data.wayback.error ? 'x' : ' '}] Wayback Machine history (${data.wayback?.totalCaptures || 0} captures)
- [${data.dns && !data.dns.error ? 'x' : ' '}] DNS reconnaissance (email provider, SPF, DMARC)
- [${data.tech ? 'x' : ' '}] Tech stack extracted (CMS, analytics, pixels)
- [${data.search ? 'x' : ' '}] Public search (USASpending, social profiles)

## What Requires Manual Research

- [ ] Revenue and financials
- [ ] Team roster and org chart
- [ ] Supplier relationships
- [ ] Customer identification
- [ ] Competitive landscape
- [ ] Industry context
- [ ] Risk assessment

> **Tip:** Add an Anthropic API key in VS Code settings (\`companyDossier.anthropicApiKey\`) to get AI-generated analysis including executive brief, SWOT, and key findings.

*This brief was auto-generated. Manual research will dramatically improve it.*
`);
  }
  count++;

  // =========================================================================
  // 11_analysis/swot.md — AI-generated SWOT
  // =========================================================================
  if (data.llmSynthesis?.swotAnalysis) {
    writeFile(path.join(dossierDir, '11_analysis', 'swot.md'), `---
title: "SWOT Analysis"
type: analysis
domain: strategic
confidence: moderate
last_updated: ${today}
generated_by: claude-sonnet-4
---

# SWOT Analysis: ${companyName}

${data.llmSynthesis.swotAnalysis}

---

*Generated by Claude (claude-sonnet-4) from automated collection data. Confidence: Moderate. Manual verification recommended.*
`);
    count++;
  }

  // =========================================================================
  // 11_analysis/key_findings.md — AI-generated findings
  // =========================================================================
  if (data.llmSynthesis?.keyFindings) {
    writeFile(path.join(dossierDir, '11_analysis', 'key_findings.md'), `---
title: "Key Intelligence Findings"
type: analysis
domain: strategic
confidence: moderate
last_updated: ${today}
generated_by: claude-sonnet-4
---

# Key Intelligence Findings: ${companyName}

${data.llmSynthesis.keyFindings}

---

*Generated by Claude (claude-sonnet-4) from automated collection data.*
`);
    count++;
  }

  return count;
}
