import * as path from 'path';
import { mkdirp, writeIfNotExists, todayISO } from '../utils';

const DIRS = [
  '_meta', '_data', '_assets/photos/people', '_assets/photos/products',
  '_assets/photos/facilities', '_assets/photos/events', '_assets/photos/brand',
  '_assets/photos/logos', '_assets/pdfs/datasheets', '_assets/pdfs/job_postings',
  '_evidence/source_data', '_evidence/bulk_datasets', '_evidence/web_scrapes/raw_html',
  '_archive',
  '1_corporate', '2_people/profiles', '3_products/categories',
  '4_suppliers/profiles', '5_customers/prospects', '6_competitors/profiles',
  '7_financials', '8_marketing/events', '9_brand', '10_timeline',
  '11_analysis', '12_industry/history', '12_industry/regulation',
  '12_industry/workforce', '12_industry/technology', '12_industry/political',
  '12_industry/synthesis'
];

const SECTIONS = [
  '1_corporate', '2_people', '3_products', '4_suppliers', '5_customers',
  '6_competitors', '7_financials', '8_marketing', '9_brand', '10_timeline',
  '11_analysis', '12_industry'
];

export function scaffoldDossier(dossierDir: string, companyName: string): number {
  let count = 0;

  for (const dir of DIRS) { mkdirp(path.join(dossierDir, dir)); }

  // _MOC.md for each section
  for (const section of SECTIONS) {
    const name = section.replace(/^\d+_/, '').replace(/_/g, ' ');
    if (writeIfNotExists(path.join(dossierDir, section, '_MOC.md'),
      `---\ntitle: "${name} — Map of Content"\ntype: moc\nsection: ${section}\nlast_updated: ${todayISO()}\n---\n\n# ${name}\n\n| File | Description |\n|------|-------------|\n`
    )) { count++; }
  }

  // _meta files
  if (writeIfNotExists(path.join(dossierDir, '_meta', 'confidence_legend.md'),
    `---\ntitle: "Confidence Legend"\ntype: reference\nlast_updated: ${todayISO()}\n---\n\n# Confidence Scale\n\n| Level | Meaning |\n|-------|---------|\n| **Definitive** | Government record, SEC filing |\n| **High** | 2+ independent credible sources |\n| **Moderate** | 1 credible source |\n| **Low** | Single non-authoritative source |\n| **Inferred** | Logical deduction |\n| **Unverified** | Uncorroborated |\n`
  )) { count++; }

  if (writeIfNotExists(path.join(dossierDir, '_meta', 'methodology.md'),
    `---\ntitle: "Research Methodology"\ntype: reference\nlast_updated: ${todayISO()}\n---\n\n# Research Methodology\n\nPublic sources only. Generated by Company Dossier VS Code Extension.\n\n## Collection Phases\n\n1. Live Site Crawl (homepage, sitemap, robots.txt)\n2. Historical Reconstruction (Wayback CDX API)\n3. DNS Reconnaissance (MX, TXT, DMARC)\n4. Tech Stack Extraction (analytics, CMS, CDN, ad pixels)\n`
  )) { count++; }

  // _data/README.md
  if (writeIfNotExists(path.join(dossierDir, '_data', 'README.md'),
    `---\ntitle: "Data Layer"\ntype: reference\nlast_updated: ${todayISO()}\n---\n\n# Data Layer\n\nAll structured data (CSVs) lives here.\n`
  )) { count++; }

  // CHANGELOG
  if (writeIfNotExists(path.join(dossierDir, 'CHANGELOG.md'),
    `---\ntitle: "Changelog"\ntype: reference\nlast_updated: ${todayISO()}\n---\n\n# Changelog\n\n## ${todayISO()} — Dossier Created\n\nGenerated by Company Dossier VS Code Extension v1.0.0\n`
  )) { count++; }

  return count;
}
